# Generated by Django 5.1.7 on 2025-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
