# Generated by Django 4.2.20 on 2025-05-01 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_bid_auction_alter_bid_bidder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="rating",
        ),
    ]
